server:
  port: 52341
  address: 0.0.0.0

spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_game?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

logging:
  level:
    org.hibernate.SQL: DEBUG