INSERT INTO t_guest_type (guest_name, dish_id, avatar, unlock_level)
SELECT '小王', 1, 'boy_1', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_guest_type LIMIT 1)
UNION ALL
SELECT '小李', 2, 'girl_1', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_guest_type LIMIT 1)
UNION ALL
SELECT '老张', 3, 'uncle_1', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_guest_type LIMIT 1)
UNION ALL
SELECT '阿花', 4, 'auntie_1', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_guest_type LIMIT 1)
UNION ALL
SELECT '小明', 1, 'boy_2', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_guest_type LIMIT 1)
UNION ALL
SELECT '小红', 2, 'girl_2', 2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_guest_type LIMIT 1)
UNION ALL
SELECT '大刘', 5, 'man_1', 3 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_guest_type LIMIT 1)
UNION ALL
SELECT '陈姐', 6, 'woman_1', 5 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_guest_type LIMIT 1);

INSERT INTO t_task (task_type, task_desc, target_count, reward_type, reward_amount)
SELECT 1, '招待3位客人', 3, 1, 2.00 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_task LIMIT 1)
UNION ALL
SELECT 1, '招待5位客人', 5, 2, 200 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_task LIMIT 1)
UNION ALL
SELECT 2, '招待10位客人', 10, 1, 5.00 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_task LIMIT 1)
UNION ALL
SELECT 2, '招待30位客人', 30, 2, 1000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM t_task LIMIT 1);
